### ISSUE TITLE
help

### ISSUE THREAD

**Issue by F1R3L1GHT** [unmutation/indinibee-discord#1]
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module './items'
Require stack:
- /Users/cencored/Downloads/in/commands/share.js

can u pls help

**Comment by unmutation** [comment]
That's because master branch's codes aren't stable and missing items.js. You can check this release which is stable. https://github.com/unmutation/indinibee-discord/tree/2020-09-07_01

I will probably create another release in a week

**Comment by F1R3L1GHT** [comment]
thank you!!

**Comment by F1R3L1GHT** [comment]
uh wait, thats the same one...

**Comment by F1R3L1GHT** [comment]
do you mind sharing the files with me on discord? my discord is Eevee!#0001

**Comment by F1R3L1GHT** [comment]
0001*

**Comment by F1R3L1GHT** [comment]
Error: Cannot find module './server'

**Comment by F1R3L1GHT** [comment]
that happens when i do that version

**Comment by F1R3L1GHT** [comment]
i deleted the keepAlive, now it works
